Add instance level range to their container title
ThePettsoN/LFGAnnouncements pull request #22
Opened 2022-08-06 19:12 UTC by mikehaney24

2022-08-10 14:11 UTC, ThePettsoN requested changes

2022-08-10 14:11 UTC, ThePettsoN commented on src/ui.lua
> +	if getn(instanceLevelRange) == 2 then
level range will always be of size 2. No need to check. (Also, since it's a array it really should be `#instanceLevelRange` for performance)

2022-08-10 14:11 UTC, ThePettsoN commented on src/ui.lua
> +	    name = stringformat("%s (%d, %d)", instanceName, instanceLevelRange[1], instanceLevelRange[2])
This will alter the actual name of the container. We don't want that. This should be done in `getGroupTitle`

2022-08-23 00:21 UTC, mikehaney24 commented
Looks like you've added the functionality, thanks!

2022-08-23 00:21 UTC, closed without merging